name: tournament_cards_website
description: Single page application with a generator that helps you create awesome tournaments.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  url_launcher: ^5.7.10
  rxdart: ^0.27.2
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  web_browser_detect: ^2.0.2
  version: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/